### ISSUE TITLE
Project file missing FSharp.Core reference

### ISSUE THREAD

**Issue by rneatherway** [gmpl/FSharpPlus#13]
This causes trouble for intellisense in Monodevelop and all editors depending on FSharp.AutoComplete.

**Comment by gmpl** [comment]
Thanks, I wasn't aware of the issue in Monodevelop.
You can always add it manually but then you're stick to a specific F# version.
Do you have any suggestion about how to fix it without targeting a specific version?

**Comment by rneatherway** [comment]
You can include a reference to just `FSharp.Core`, but if you don't use `CopyLocal` then I don't know what the difference would be? It will just be chosen non-deterministically when you build instead.

**Comment by gmpl** [comment]
Thanks, can you try it?
I don't have Monodevelop, but if you try it and it works send me a pull request and I will accept it.

**Comment by rneatherway** [comment]
It does work, but which version of FSharp.Core do you *really* want to require? If you look at this page it explains some things about how to handle FSharp.Core: https://fsharp.github.io/2015/04/18/fsharp-core-notes.html

I suggest targeting 4.3 (F# 3.0), which places minimal requirements on consumers of your library.

**Comment by gmpl** [comment]
I agree, 4.3 should be the minimal. Thanks for the link.
