### ISSUE TITLE
`>>=` tends to throw bizarre error in mono

### ISSUE THREAD

**Issue by mjgpy3** [gmpl/FSharpPlus#20]
This library is really cool! Thank you for all the hard work.

I'm not sure if this library claims to support mono or not. But I'm getting a strange error whenever I use the `>>=` and `=<<` operators. Surprisingly this error occurs even if I annotate types.

The error is:
> FSC: error FS0192: internal error: GenUnionRef m

**Comment by gmpl** [comment]
Thanks for your feedback !
I don't think that error has to do with type inference, that's something really internal, at runtime.
I've seen that error before when using code compiled with a different version of FsControl which is not backward compatible. Typically when there was a change in the DU which is used internally to define the overloads.
Regarding mono, the library doesn't claim it supports mono but I don't see any reason why it shouldn't, there is a [build in mono](https://travis-ci.org/gmpl/FSharpPlus) and it's not failing so one thing you can do is fork the lib, add a test with the failing code and see if it fails the build as well.

Let me know how it goes.

**Comment by mjgpy3** [comment]
Yep, you're correct. The following example is working as a Sample:
```
let dividedInto a b =
  match a with
    | 0 -> Choice2Of2 "Cannot divide by 0"
    | _ -> Choice1Of2 (b / a)

let shouldntCauseGenRef =
    Choice1Of2 42
      |> fun a -> a >>= (dividedInto 99)
```

But if I stick it in my project it union refs. I'll try to figure out which version of FsControl ought to be used. Thank you for the help!
