### ISSUE TITLE
Build Script Errors when compiling on Mono

### ISSUE THREAD

**Issue by dogwith1eye** [gmpl/FSharpPlus#26]
I'm running into few build script errors in the build.fsx file when compiling on Mono version 4.6.2

**Extra quote at end of build.fsx**

```
bash-3.2$ sudo ./build.fsx
build.fsx(76,42): error FS0514: End of file in string begun at or before here
```

Which is easily fixed by removing the extraneous quote at the end of the file

exec fakeExe ("makefile.fsx"::passedArgs)"
------------------------------------------^

**TypeInitializationException in applyExecutionPermissionUnix**

```
let applyExecutionPermissionUnix path =
    let _,stat = Syscall.lstat(path)
    Syscall.chmod(path, FilePermissions.S_IXUSR ||| stat.st_mode) |> ignore

System.TypeInitializationException: The type initializer for 'Mono.Unix.Native.Syscall' threw an exception
```

Commenting out the applyExecutionPermissionUnix function lets me build fine, which makes me wonder whether it's really a necessary step.

**Comment by gmpl** [comment]
Thanks for testing it in Mono.
You can submit a PR to correct that file.
Alternatively we can re-create the solution from scratch using the [F# Project Scaffold](http://fsprojects.github.io/ProjectScaffold/) which include build scripts for all platforms.

**Comment by dogwith1eye** [comment]
I think it makes more sense to re-create with the the f# project scaffolding. I can submit a PR for that if you like.

**Comment by gmpl** [comment]
It would be great if you can submit that PR.
Then we will have paket, docs and tests.
That would be very useful because we will be merging FsControl here soon, which has already unit tests and some docs.

**Comment by gmpl** [comment]
I guess this is fixed now by https://github.com/gmpl/FSharpPlus/commit/2fb9bcdc13b93fefed23614eb9b049d78c914d23 otherwise please re-open.
